package com.salesmanager.drools.rules;

import com.salesmanager.core.business.modules.order.total.OrderTotalInputParameters;

global com.salesmanager.core.business.modules.order.total.OrderTotalResponse total;

dialect  "mvel"

rule "DISCOUNT"
    when
        order: OrderTotalInputParameters(discount > 0)
    then
        total.setDiscount(order.getDiscount());
end

rule "TRANHONGQUANG"
    when
        OrderTotalInputParameters(promoCode == 'TRANHONGQUANG')
    then
        total.setDiscount(0.50);
end
